title: "양재천 수달 보호 단체"
labels: [Discussions]
body:
- type: textarea
  id: Description
  attributes:
    label: Bugs Description
    description: 버그 상황에 대해 자세히 써주세요
    value: |
      1. 버그 발생한 OS
      2. 버그 상황 설명
      ...
    render: bash
  validations:
    required: true
- type: textarea
  id: BDD_TASK
  attributes:
    label: BDD TASK
    description: BDD TASK
    value: |
      1. BDD 작성은 given > when > then 순으로 작성해주세요 :)
      2. ...
      ...
    render: bash
  validations:
    required: true
