title: "양재천 수달 보호 단체"
labels: [Discussions]
body:
- type: textarea
  id: Description
  attributes:
    label: Bugs Description
    description: 버그 상황에 대해 자세히 써주세요
    value: |
      1. 버그 발생한 OS
      2. 버그 상황 설명
      ...
    render: bash
  validations:
    required: true
- type: markdown
  attributes: 
    value: |
      [ ] 구체적인 동작을 작성해주세요(ex. 초기화 버튼을 누르면 디폴트 값으로 적용된다)
