title: "양재천 수달 보호 단체"
labels: [Discussions]
body:
- type: markdown
  attributes: 
   value: |
     [참고 레퍼런스](https://github.com/community/community/blob/main/.github/DISCUSSION_TEMPLATE/discussions.yml)
- type: dropdown
  attributes:
    label: 주제
    description: 주제가 무엇인가요?
    options:
      - "Announcements"
      - "Bugs"
      - "Q&A"
      - "Show & Tell"
      - "General"
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: 자유롭게 이야기를 나눠봐요!
  validations:
    required: true
- type: checkboxes
  id: BDD-Check
  attributes:
    label: 체크 목록!
    options:
      - label: 구체적인 동작을 작성해주세요!
        required: true
      - label: 구체적인 동작을 작성해주세요 - 2!
