title: "양재천 수달 보호 단체"
labels: [Discussions]
body:
- type: dropdown
  attributes:
    label: 주제
    description: 주제가 무엇인가요?
    options:
      - "Features"
      - "General"
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: 자유롭게 이야기를 나눠봐요 (ex. 기능 개발 제안, 질문 등등)!
  validations:
    required: true
- type: textarea
  id: BDD_TASK
  attributes:
    label: BDD TASK
    description: BDD 작성은 given > when > then 순으로 작성해주세요 :)
    value: |
      1. Features시 BDD 작성 부탁드립니다.
      2. ...
      ...
    render: bash
  validations:
    required: false
